// Generated by CoffeeScript 1.6.3
var mongoose;

mongoose = require('mongoose');

module.exports = {
  User: require('./user'),
  OAuthProfile: require('./oauth_profile'),
  ObjectId: function(x) {
    var e;
    try {
      return new mongoose.Schema.Types.ObjectId(x);
    } catch (_error) {
      e = _error;
      return null;
    }
  }
};
